version: '3'
services:
  app:
    build: ./
    working_dir: /src/app
    command: ./node_modules/nodemon/bin/nodemon.js ./index.js
    volumes:
      - .:/src/app
      - /src/app/node_modules
    ports:
      - 8000:3000
    depends_on:
      - mongo
    networks:
      - pounds-network
  
  mongo:
    image: mongo
    restart: always
    environment:
      - .local.env
    networks:
      - pounds-network
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      - .local.env
    networks:
      - pounds-network

networks: 
  pounds-network:
